language: shell

env:
  global:
    - CIBW_SKIP="cp27* cp35* cp38*"
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD should be set to an API token in the Travis settings
  jobs:
    - CONDA_PYTHON=3.6
    - CONDA_PYTHON=3.7

os:
  - linux

stages:
  - test
  - name: deploy
    if: tag IS PRESENT AND repo = TheBB/IFEM-to-VT

before_install:
  - source ./ci/before_install.sh

install:
  - source ./ci/install.sh
  - conda install -y python=${CONDA_PYTHON} h5py
  - pip install vtk>=9
  - pip install pytest
  - pip install twine cibuildwheel==1.1.0
  - conda list

script:
  - python setup.py install
  - pytest

jobs:
  include:
    - stage: deploy
      name: Deploy source distribution
      script: python setup.py sdist --formats=gztar
      after_success: python -m twine upload --skip-existing dist/*.tar.gz
    - stage: deploy
      name: Build and deploy Linux wheels
      services: docker
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl

notifications:
  email:
    on_success: never
    on_failure: never
